config/routes.rb
# config/routes.rb

Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "recipes#index"

  resources :foods, except: [:update]
  get '/general_shopping_lists', to: 'general_shopping_lists#index'
  resources :public_recipes, only: [:index]
  resources :recipes, except: [:update] do
    resources :recipe_foods, only: [:new, :create, :destroy]
    member do
      post 'toggle_public'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, :unit, :price, :quantity, presence: true
  validates :price, :quantity, numericality: { only_integer: true }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods # Correct the association name to plural (foods)

  validates :name, presence: true
  validates :preparation_time, presence: true, numericality: { only_integer: true }
  validates :cooking_time, presence: true, numericality: { only_integer: true }
  validates :description, presence: true
  validates :user_id, presence: true
  validates :public, inclusion: { in: [true, false] }

  def total_price
    foods.sum(:price)
  end

  def total_food_items
    recipe_foods.count
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :food_id, :recipe_id, presence: true
  validates :quantity, presence: true, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Devise::Controllers::Helpers

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public, :user_id)
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  def index
    @foods = current_user.foods.includes(:recipe_foods)
    @new_food = Food.new
  end

  def show; end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user = current_user

    if @food.save
      redirect_to foods_path, notice: 'Food was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def destroy
    @food = current_user.foods.find(params[:id])
    @food.destroy
    redirect_to foods_path, notice: 'Food was successfully destroyed.'
  end

  private

  def food_params
    params.require(:food).permit(:name, :unit, :price, :quantity)
  end
end

app/controllers/general_shopping_lists_controller.rb
class GeneralShoppingListsController < ApplicationController
  MissingFood = Struct.new(:food, :quantity)

  def index
    @user = current_user

    begin
      @missing_foods = calculate_missing_foods(@user)
      @shopping_list_items = @missing_foods.map do |item|
        Struct.new(food: item.food, quantity: item.quantity)
      end
      @total_food_items = @missing_foods.sum(&:quantity)
      @total_price = @missing_foods.sum { |food| food.quantity * food.food.price }
    rescue StandardError => e
      Rails.logger.error("Error calculating missing foods: #{e.message}")
      flash[:alert] = 'An error occurred while calculating missing foods.'
      redirect_to root_path
    end
  end

  private

  def calculate_missing_foods(user)
    user_recipes = Recipe.where(user:).includes(:recipe_foods)
    user_food_ids = user.foods.pluck(:id)
    recipe_food_ids = RecipeFood.where(recipe: user_recipes).pluck(:food_id)
    missing_food_ids = (recipe_food_ids - user_food_ids).uniq
    missing_foods = Food.where(id: missing_food_ids).includes(:recipes)

    missing_foods.map do |food|
      MissingFood.new(
        food,
        user_recipes.sum { |recipe| recipe.recipe_foods.find_by(food:)&.quantity.to_i }
      )
    end
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.where(public: true).includes(:user, :recipe_foods, :foods).order(created_at: :desc)
  end

  def show; end

  def destroy
    @recipe = Recipe.find(params[:id])
    if current_user == @recipe.user
      @recipe.destroy
      redirect_to public_recipes_path, notice: 'Recipe was successfully deleted.'
    else
      redirect_to public_recipes_path, alert: 'You are not authorized to delete this recipe.'
    end
  end
end

app/controllers/recipe_foods_controller.rb
# app/controllers/recipe_foods_controller.rb

class RecipeFoodsController < ApplicationController
  before_action :set_recipe

  def new
    @recipe_food = RecipeFood.new
  end

  def create
    @recipe_food = @recipe.recipe_foods.build(recipe_food_params)

    if @recipe_food.save
      redirect_to recipe_path(@recipe), notice: 'Recipe food was successfully added.'
    else
      render :new
    end
  end

  def edit
    @recipe_food = @recipe.recipe_foods.includes(:food).find(params[:id])
  end

  def update
    @recipe_food = @recipe.recipe_foods.find(params[:id])

    if @recipe_food.update(recipe_food_params)
      redirect_to @recipe, notice: 'Ingredient was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    redirect_to @recipe, notice: 'Ingredient was successfully removed.'
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = current_user.recipes
  end

  def show
    @recipe = Recipe.includes(recipe_foods: :food).find(params[:id])
    redirect_to recipes_path unless @recipe.public || (user_signed_in? && current_user == @recipe.user)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)

    if @recipe.save
      redirect_to @recipe, notice: 'Recipe was successfully created.'
    else
      render :new
    end
  end

  def edit
    @recipe = Recipe.includes(recipe_foods: :food).find(params[:id])
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    if current_user == @recipe.user
      @recipe.update(public: !@recipe.public)
      redirect_back fallback_location: recipes_path
    else
      redirect_back fallback_location: recipes_path,
                    alert: 'You are not authorized to toggle the visibility of this recipe.'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    if current_user == @recipe.user
      @recipe.destroy
      redirect_to recipes_url, notice: 'Recipe was successfully destroyed.'
    else
      redirect_to recipes_url, alert: 'You are not authorized to destroy this recipe.'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/views/foods/_form.html.erb
<%= form_with(model: @food, url: foods_path, local: true) do |form| %>
  <% if @food && @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, 'error') %> prohibited this food from being saved:</h2>
      <ul>
        <% @food.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :unit %>
    <%= form.text_field :unit %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Edit Food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<div style="display: flex; justify-content:end; margin: 25px">
<%= link_to 'Add Food', new_food_path, class: 'btn-link' %>
</div>
<table>
 <% if @foods && @foods.any? %>
 <thead>
 <tr>
          <th>Food</th>
          <th>Measurement Unit</th>
          <th>Unit Price</th>
          <th>Actions</th>
        </tr>
</thead>
<tbody>
    <% @foods.each do |food| %>
      <tr>
        <td>
        <%= food.name %>
        </td>
        <td>
        <%= food.unit %>
        </td>
        <td>
        <%= number_to_currency(food.price) %>
        </td>
        <td>
         <%= link_to 'Delete', food_path(food), data: { turbo_method: :delete, confirm:'are you sure you want to delete this?' }%>
        </td>
      </tr>
    <% end %>
  </tbody>
  <% else %>
    <li>No foods available.</li>
  <% end %>
</table>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/general_shopping_lists/index.html.erb
<h1>General Shopping List</h1>
<div class="flex">
<p>Total Food Items: <%= @total_food_items %></p>
<p>Total Value: <%= number_to_currency(@total_value) %></p>
</div>
<table>
  <thead>
    <tr>
      <th>Food</th>
      <th>Total Quantity</th>
      <th>Total Price</th>
    </tr>
  </thead>
  <tbody>
    <% @shopping_list_items.each do |item| %>
      <tr>
        <td><%= item.food.name %></td>
        <td><%= item.quantity %> <%= item.food.measurement_unit %></td>
        <td><%= number_to_currency(item.quantity * item.food.price) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if user_signed_in? %>
  <div class= "flex">
<div>Welcome <%= current_user.name %></div>
  <div>
  <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete } %>
  </div>
  </div>
<% end %>
<nav>
    <ul>
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'Foods', foods_path %></li>
      <li><%= link_to 'Public Recipes', public_recipes_path %></li>
<li><%= link_to 'General Shopping List', general_shopping_lists_path %> </li>     <!-- Add other navigation links as needed -->
    </ul>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/public_recipes/index.html.erb
<h1>List of Public Recipes</h1>

<ul>
  <% @public_recipes.each do |recipe| %>
    <li class= 'food-border'>
    <div>
      <strong><%= link_to recipe.name, recipe_path(recipe) %></strong> <br>
      Created by: <%= recipe.user.name %>

      <% if current_user == recipe.user %>
        <div>
         <%= link_to 'Delete', recipe_path(recipe), method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      <% end %>
      </div>
    <div>
     <strong>Total Food Items:</strong> <%= recipe.total_food_items %><br>
      <strong>Total Price:</strong> <%= number_to_currency(recipe.total_price) %>
    </div>
     
    </li>
  <% end %>
</ul>

app/views/recipe_foods/_form.html.erb
<%= form_with(model: [ @recipe, recipe_food ], local: true) do |form| %>
  <% if recipe_food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe_food.errors.count, "error") %> prohibited this recipe food from being saved:</h2>

      <ul>
        <% recipe_food.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :food_id %>
    <%= form.collection_select :food_id, Food.all, :id, :name, prompt: 'Select a food' %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipe_foods/new.html.erb
<h1>New Recipe Food</h1>

<%= render 'form', recipe_food: @recipe_food %>

<%= link_to 'Back', recipe_path(@recipe) %>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :preparation_time, "Preparation time (in mins)"  %>
    <%= form.number_field :preparation_time %>
  </div>

  <div class="field">
    <%= form.label :cooking_time, "Cooking time (in mins)"  %>
    <%= form.number_field :cooking_time %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :public %>
    <%= form.check_box :public %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe  %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Your Recipes</h1>
 
<% if @recipes.present? %>
  <ul class="container">
    <% @recipes.each do |recipe| %>
  <li class="food-border">
  <div>
  <div>
  <%= link_to recipe.name, recipe_path(recipe) %>
  </div>
    <div class='remove-div'>
        <%= link_to 'REMOVE', recipe_path(recipe), data: { turbo_method: :delete, confirm:'are you sure you want to delete this?' } %>
    </div>
  </div>
  <div>
  <%= recipe.description%>
  </div>
  </li>
<% end %>
  </ul>
<% else %>
  <p>You haven't created any recipes yet.</p>
<% end %>

<%= link_to 'Create New Recipe', new_recipe_path, class: 'btn btn-success' %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>


<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>
<% if current_user == @recipe.user || @recipe.public %>
  <p>
    <strong>Preparation Time:</strong> <%= @recipe.preparation_time %> minutes<br>
    <strong>Cooking Time:</strong> <%= @recipe.cooking_time %> minutes<br>
    <strong>Public:</strong> <%= @recipe.public ? 'Yes' : 'No' %><br>
  </p>
  

  <% if current_user == @recipe.user %>
  <%= button_to toggle_public_recipe_path(@recipe), method: :post, class: @recipe.public ? 'public' : 'private' do %>
    <%= @recipe.public ? 'Make Private' : 'Make Public' %>
  <% end %>
  <div class="flex">
      <%= link_to 'Get Shopping List',  general_shopping_lists_path(@recipe), method: :get, class: 'btn-link' %>
    <%= link_to 'Add Ingredients', new_recipe_recipe_food_path(@recipe), class: 'btn-link' %>
  </div>
    <table>
      <thead>
        <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Value</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @recipe.recipe_foods.each do |recipe_food| %>
          <tr>
            <td><%= recipe_food.food.name %></td>
            <td><%= recipe_food.quantity %></td>
            <td><%= number_to_currency(recipe_food.quantity * recipe_food.food.price) %></td>
            <% if recipe_food.recipe.user_id == current_user.id%>
              <td class='inline' style='display: flex;'>
  <%= link_to "Modify", edit_food_path(recipe_food.food_id), class:'edit-btn'  %>
  <%= button_to "Remove", [@recipe, recipe_food], method: :delete %>
</td>

            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
<% else %>
  <p>This recipe is private.</p>
<% end %>
<%= link_to 'Back', recipes_path %>